# Site settings
name: Shakil Ahmed
title: Shakil Ahmed | Full Stack Dev & AI Researcher
description: full stack developer & AI researcher focused on building building web services & intelligent machine
url: "https://shakilahmmeed.github.io/"
baseurl: ""
email: shakil.hv@gmail.com
cover: https://shakilahmmeed.github.io/img/og.png
logo: https://shakilahmmeed.github.io/img/emojis/technologist.png
resume: https://shakilahmmeed.github.io/resume.pdf
social:
  - title: email
    url: shakil.hv@gmail.com
  - title: twitter
    url: https://twitter.com/shakilahmmeed
  - title: instagram
    url: https://instagram.com/shakilahmmeed
  - title: Facebook
    url: https://facebook.com/shakilahmmeed
  - title: github
    url: https://github.com/shakilahmmeed
  - title: linkedin
    url: https://www.linkedin.com/in/shakilahmmeed

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
